name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: virtuslab/scala-cli:0.1.15

    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: scala-cli package -f --native -o hiergraph  GraphQuery.scala
    - name: Test
      run: ./test
